language: node_js
sudo: true
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: gae
  keyfile: gae.json
  project: pro-bruin-207112
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_b33ea5ae927b_key -iv $encrypted_b33ea5ae927b_iv
  -in gae.json.enc -out gae.json -d
