language: node_js
sudo: true
node_js:
  - stable
cache:
  directories:
    - node_modules

# Decrypt Google API key
before_install:
  - openssl aes-256-cbc -K $encrypted_fb95c9318e23_key -iv $encrypted_fb95c9318e23_iv
    -in gae.json.enc -out gae.json -d

# Deploy to Google App Engine

deploy:
  provider: gae
  keyfile: gae.json
  project: pro-bruin-207112
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - npm test
